name: Build Android APK

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-android:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        api-level: 35
        build-tools: 35.0.0
        
    - name: Accept Android SDK licenses
      run: yes | sdkmanager --licenses || echo "Failed to accept licenses"

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build
      env:
        NODE_ENV: production

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew

    - name: Clean Gradle cache
      run: cd android && ./gradlew clean

    - name: Build debug APK with timeout
      run: cd android && timeout 1800 ./gradlew assembleDebug --no-daemon --stacktrace --info --parallel
      env:
        GRADLE_OPTS: -Xmx4096m -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true

    - name: Build release APK
      run: cd android && ./gradlew assembleRelease --no-daemon --stacktrace --info --parallel
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      env:
        GRADLE_OPTS: -Xmx4096m -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true

    - name: Upload debug APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: android/app/build/outputs/apk/debug/app-debug.apk

    - name: Upload release APK artifact  
      uses: actions/upload-artifact@v4
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/app-release-unsigned.apk

    - name: Build Summary
      run: |
        echo "Build completed successfully!"
        echo "Debug APK: android/app/build/outputs/apk/debug/app-debug.apk"
        if [ "${{ github.ref }}" == "refs/heads/main" ] || [ "${{ github.ref }}" == "refs/heads/master" ]; then
          echo "Release APK: android/app/build/outputs/apk/release/app-release-unsigned.apk"
        fi