name: Quick APK Build

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: npm ci

    - name: Build web app
      run: npm run build

    - name: Sync Capacitor
      run: npx cap sync android

    - name: Create keystore
      run: |
        mkdir -p android/app
        keytool -genkey -noprompt \
          -keystore android/app/debug.keystore \
          -keyalg RSA -keysize 2048 -validity 10000 \
          -alias androiddebugkey \
          -storepass android -keypass android \
          -dname "CN=Debug,OU=Debug,O=Debug,L=Debug,S=Debug,C=US"

    - name: Build APK
      run: |
        cd android
        chmod +x gradlew
        ./gradlew assembleDebug --no-daemon --no-build-cache

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: signed-apk-${{ github.run_number }}
        path: android/app/build/outputs/apk/debug/*.apk
        retention-days: 30

    - name: Build info
      run: |
        echo "APK build completed!"
        echo "Download from: Actions > This run > Artifacts"
        find android/app/build/outputs/apk -name "*.apk" -exec ls -lh {} \;